version: 2
updates:
  - package-ecosystem: pip
    directory: '/docker'
    schedule:
      interval: monthly
    ignore:
      - dependency-name: none
  - package-ecosystem: pip
    directory: '/ci'
    schedule:
      interval: monthly
    ignore:
      - dependency-name: none

  - package-ecosystem: docker
    directory: '/docker'
    schedule:
      interval: monthly
    ignore:
      - dependency-name: none
