[tool.ruff]
target-version = "py310"

[tool.poetry]
name = "operator-shared-config-manager"
version = "0.0.0"
description = "Operator Shared Config Manager"
authors = ["Camptocamp <info@camptocamp.com>"]
