inherits:
  - duplicated
  - utils:base
  - utils:fix
  - utils:no-design-checks

mypy:
  options:
    python_version: '3.10'

ruff:
  disable:
    - TRY400 # Use `logging.exception` instead of `logging.error`, catch for kopf Logger
pyroma:
  run: false
