{{- if .Values.clusterrole }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "operator-shared-config-manager.fullname" . }}
  labels:
    {{- include "operator-shared-config-manager.labels" . | nindent 4 }}
rules:
  - apiGroups:
      - ""
    resources:
      - events
    verbs:
      - create
      - list
      - watch
  - apiGroups:
      - ""
    resources:
      - configmaps
    verbs:
      - get
      - create
      - patch
      - delete
  - apiGroups:
      - camptocamp.com
    resources:
      - sharedconfigsources{{ .Values.crd.suffix }}
      - sharedconfigconfigs{{ .Values.crd.suffix }}
    verbs:
      - get
      - list
      - watch
      - patch
{{- if .Values.externalSecret }}
  - apiGroups:
      - external-secrets.io
    resources:
      - externalsecrets
    verbs:
      - get
      - create
      - patch
      - delete
{{- end }}
{{- end }}
