apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "operator-shared-config-manager.fullname" . }}
  labels:
    {{- include "operator-shared-config-manager.labels" . | nindent 4 }}
rules:
  - apiGroups:
      - ""
    resources:
      - configmaps
    verbs:
      - get
      - create
      - update
      - delete
  - apiGroups:
      - camptocamp.com
    resources:
      - sharedconfigsources
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - camptocamp.com
    resources:
      - sharedconfigconfigs
    verbs:
      - get
      - list
      - watch
