{{- if .Values.crd }}
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: sharedconfigsources.camptocamp.com
  labels:
    {{- include "operator-shared-config-manager.labels" . | nindent 4 }}
spec:
  group: camptocamp.com
  versions:
    - name: v2
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              required:
                - environment
                - name
                - content
              properties:
                environment:
                  type: string
                name:
                  type: string
                content:
                  type: object
                  x-kubernetes-preserve-unknown-fields: True
            status:
              x-kubernetes-preserve-unknown-fields: true
  scope: Namespaced
  names:
    plural: sharedconfigsources
    singular: sharedconfigsource
    kind: SharedConfigSource
    shortNames:
      - scs
{{- end }}
