{{- if .Values.crd.enabled }}
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: sharedconfigsources{{ .Values.crd.suffix }}.camptocamp.com
  labels:
    {{- include "operator-shared-config-manager.labels" . | nindent 4 }}
spec:
  group: camptocamp.com
  versions:
    - name: v4
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              required:
                - name
                - content
              properties:
                name:
                  type: string
                content:
                  type: object
                  x-kubernetes-preserve-unknown-fields: true
                external_secret:
                  type: object
                  additionalProperties:
                      type: string
            status:
              x-kubernetes-preserve-unknown-fields: true

    - name: v3
      served: true
      storage: false
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              required:
                - name
                - content
              properties:
                name:
                  type: string
                content:
                  type: object
                  x-kubernetes-preserve-unknown-fields: true
            status:
              x-kubernetes-preserve-unknown-fields: true
    - name: v2
      served: true
      storage: false
      deprecated: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              required:
                - name
                - content
              properties:
                environment:
                  type: string
                name:
                  type: string
                content:
                  type: object
                  x-kubernetes-preserve-unknown-fields: true
            status:
              x-kubernetes-preserve-unknown-fields: true
    - name: v1
      served: true
      storage: false
      deprecated: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                name:
                  type: string
                content:
                  type: object
                  x-kubernetes-preserve-unknown-fields: true
            status:
              x-kubernetes-preserve-unknown-fields: true
  scope: Namespaced
  names:
    plural: sharedconfigsources{{ .Values.crd.suffix }}
    singular: sharedconfigsource{{ .Values.crd.suffix }}
    kind: SharedConfigSource{{ .Values.crd.suffix | title }}
    shortNames:
      - scs{{ .Values.crd.shortSuffix }}
{{- end }}
