{{- if .Values.crd.enabled }}
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: sharedconfigconfigs{{ .Values.crd.suffix }}.camptocamp.com
  labels:
    {{- include "operator-shared-config-manager.labels" . | nindent 4 }}
spec:
  group: camptocamp.com
  versions:
    - name: v3
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              required:
                - matchLabels
                - property
                - configmapName
              properties:
                matchLabels:
                  type: object
                  additionalProperties:
                    type: string
                property:
                  type: string
                configmapName:
                  type: string
            status:
              x-kubernetes-preserve-unknown-fields: true
    - name: v2
      served: true
      storage: false
      deprecated: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              required:
                - matchLabels
                - property
                - configmapName
              properties:
                environment:
                  type: string
                matchLabels:
                  type: object
                  additionalProperties:
                    type: string
                property:
                  type: string
                configmapName:
                  type: string
            status:
              x-kubernetes-preserve-unknown-fields: true
    - name: v1
      served: true
      storage: false
      deprecated: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                matchLabels:
                  type: object
                  additionalProperties:
                    type: string
                property:
                  type: string
                configmapName:
                  type: string
            status:
              x-kubernetes-preserve-unknown-fields: true
  scope: Namespaced
  names:
    plural: sharedconfigconfigs{{ .Values.crd.suffix }}
    singular: sharedconfigconfig{{ .Values.crd.suffix }}
    kind: SharedConfigConfig{{ .Values.crd.suffix | title }}
    shortNames:
      - scc{{ .Values.crd.shortSuffix }}
{{- end }}
