{{- if .Values.crd }}
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: sharedconfigconfigs.camptocamp.com
  labels:
    {{- include "operator-shared-config-manager.labels" . | nindent 4 }}
spec:
  group: camptocamp.com
  versions:
    - name: v2
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              required:
                - environment
                - matchLabels
                - property
                - configmapName
              properties:
                environment:
                  type: string
                matchLabels:
                  type: object
                  additionalProperties:
                    type: string
                property:
                  type: string
                configmapName:
                  type: string
            status:
              x-kubernetes-preserve-unknown-fields: true
    - name: v1
      served: true
      storage: false
      deprecated: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                matchLabels:
                  type: object
                  additionalProperties:
                    type: string
                property:
                  type: string
                configmapName:
                  type: string
            status:
              x-kubernetes-preserve-unknown-fields: true
  scope: Namespaced
  names:
    plural: sharedconfigconfigs
    singular: sharedconfigconfig
    kind: SharedConfigConfig
    shortNames:
      - scc
{{- end }}
