apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: sharedconfigconfigs.camptocamp.com
  labels:
    {{- include "operator-shared-config-manager.labels" . | nindent 4 }}
spec:
  group: camptocamp.com
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                matchLabels:
                  type: object
                  additionalProperties:
                    type: string
                property:
                  type: string
                configmap_name:
                  type: string
  scope: Namespaced
  names:
    plural: sharedconfigconfigs
    singular: sharedconfigconfig
    kind: SharedConfigConfig
    shortNames:
      - scc
