apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "operator-shared-config-manager.serviceAccountName" . }}
  labels:
    {{- include "operator-shared-config-manager.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
