#!/bin/bash -eu

kubectl config set-context --current --namespace=default
kubectl get pods --output=wide

for name in $(kubectl get pods --output=name)
do
  echo =====================
  echo $name
  kubectl logs $name
done
